/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class DramPufJni */

#ifndef _Included_DramPufJni
#define _Included_DramPufJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     DramPufJni
 * Method:    genKey
 * Signature: (Ljava/lang/String;III[Ljava/lang/String;ILjava/lang/String;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_DramPufJni_genKey
  (JNIEnv *, jobject, jstring, jint, jint, jint, jobjectArray, jint, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
