name: Build Firmware

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: hyperspeeed/vc4-toolchain
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Compile firmware
      run: |
           cd covert-channel-code/rpi-open-firmware-master
           ./buildall.sh
           cd ../..

    - name: Compile kernel
      run: |
           cd covert-channel-code/kernel
           make
           cd ../..

    - name: Reorganise boot folder
      run: |
           mkdir boot
           cp covert-channel-code/rpi-open-firmware-master/build/*.bin boot/
           cp covert-channel-code/kernel/*.img boot/
           cp SDCard/* boot/

    - name: Upload boot files
      uses: actions/upload-artifact@v4
      with:
        name: Boot Files
        path: boot/*
